### ISSUE TITLE
Expanding Features

### ISSUE THREAD

**Issue by AZaletski24** [Tvick22/platformer3x#3]
- See how we can add potential ranking system
- Look into gameend to see if we can make leaderboard automatically appear
- Remove the link that closes the leaderboard, redundant to have both a toggle button and a remove link
- Add more potential features to this issue as updates arise

**Comment by katelyngelle** [comment]
- Possibly add easier directional jumping so that the sprite doesn't merely rise in a vertical line
- Clean up animation of sprite when it enters a tube
